- hosts: all
  become: yes
  tasks:
    - package: 
        name: "httpd"
        state: present
    - copy: 
         dest: "/var/www/html/text.txt"
         src: "text.txt"
    - replace:
         path: "/etc/httpd/conf/httpd.conf"
         regexp: "AllowOverrider None"
         replace: "AllowOverride AuthConfig"
    - copy:
         dest: "/var/www/html/.htaccess"
         src: ".htaccess"  

